analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.60007
title: Digital Marketing Gurus
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.0625
  brandStrength: 0.6875
  rhythmicContrast: 0.9332868887577206
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.9139834851957858
purpose: []
favicon: null
name: poweroftwo
typography_spectrum: 0.39459
